server:
  port: 8088
  servlet:
    context-path: /api/

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/java?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: java_scope
    password: wellstest1



mybatis:
  #mapper.xml所在位置
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.wells.common


pagehelper:
  reasonable: true
  params: count=countSql
  support-methods-arguments: true
  helper-dialect: mysql
