server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/node
    username: root
    password: admin

mybatis:
  #mapper.xml所在位置
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.wells.common